

import React from 'react';
import type { Card } from './types';
import { CardType } from './types';
import { ThemeIcon, GenreIcon, CharacterIcon, PlotIcon, StructureIcon, TechniqueIcon, EndingIcon, UserCircleIcon, ArrowsRightLeftIcon, GlobeAltIcon, FireIcon, Bars3BottomLeftIcon } from './components/icons';

export const CORE_CARD_TYPES: CardType[] = [CardType.Theme, CardType.Genre, CardType.Character, CardType.Plot];
export const OPTIONAL_CARD_TYPES: CardType[] = [CardType.Structure, CardType.Technique, CardType.Ending, CardType.Inspiration];

export const CARD_TYPE_NAMES: Record<CardType, string> = {
    [CardType.Theme]: '主题',
    [CardType.Genre]: '类型',
    [CardType.Character]: '角色',
    [CardType.Plot]: '情节',
    [CardType.Structure]: '叙事结构',
    [CardType.Technique]: '叙事手法',
    [CardType.Ending]: '结局',
    [CardType.Inspiration]: '灵感集 (可选)',
};

export const BRAINSTORM_TOOLS = [
    {
        id: 'character',
        name: '角色深潜',
        description: '深入挖掘角色的动机、矛盾与背景故事。',
        icon: <UserCircleIcon className="w-6 h-6" />,
        systemPrompt: '你是一位经验丰富的小说编辑，擅长通过提问来帮助作者深化角色。你的回答应该简洁、具有启发性，并始终以开放式问题结尾，引导用户思考。',
        initialMessage: '你好！让我们来深入探索你的角色吧。请先告诉我这个角色的基本设定，比如他/她的名字、职业和最大的愿望是什么？',
    },
    {
        id: 'plot',
        name: '情节风暴',
        description: '生成颠覆性场景，打破思维定式。',
        icon: <ArrowsRightLeftIcon className="w-6 h-6" />,
        systemPrompt: "你是一个充满奇思妙想的创意引擎。你的任务是针对用户遇到的情节瓶颈，生成多个颠覆性的 'What If...?' (如果...会怎样?) 场景。每个场景都要简短、有力，并能激发新的故事可能性。",
        initialMessage: "情节卡壳了？没关系，我们来一场头脑风暴！告诉我你现在卡住的情节是什么，比如：‘主角需要进入一座守卫森严的城堡，但不知道怎么进去。’ 我会为你提供一些意想不到的思路。",
    },
    {
        id: 'world',
        name: '世界构建',
        description: '为故事世界增添独特的规则、文化与细节。',
        icon: <GlobeAltIcon className="w-6 h-6" />,
        systemPrompt: '你是一位世界构建大师，知识渊博，想象力丰富。你会帮助用户为他们的故事世界添加独特而可信的细节。你的回答应该具体、富有画面感，并能引申出更多相关的设定。',
        initialMessage: '让我们一起构建一个令人难忘的世界吧！请先描述一下你的世界的基本样貌。它是奇幻王国，是赛博朋克都市，还是别的什么？告诉我它的核心特点，我们可以从那里开始。',
    },
    {
        id: 'worse',
        name: '还能更糟吗',
        description: '基于当前困境，生成五个让情况更糟的可能性。',
        icon: <FireIcon className="w-6 h-6" />,
        systemPrompt: '### 角色：创意写作助手情节设计专家\n### 背景：我的故事目前进展到以下内容\n### 任务：\n基于“还能更糟吗？“的原则，请帮我头脑风暴，想出五种能让当前情况变得更加糟糕、更具戏剧性或更出乎意料的可能性。\n请从不同角度思考，例如：\n* **外部冲突加剧：**（比如：出现新的敌人、环境突变、时间限制等）\n* **内部冲突激化：**（比如：主角的旧伤复发、道德困境加深、队友背叛等）\n* **引入新麻烦：**（比如：节外生枝的新问题、无辜者被卷入、之前的言被揭穿等）\n* **失去关键物品/信息/优势：**\n### 转出要求：\n请以列表形式给出具体的“更糟糕“情况，并简要说明它为什么更糟。\n### 重要：\n    -   可以添加一些自然的语言瑕疵，比如口语化表达或轻微的语法不规范，避免过于完美。\n    -   不要有AI味儿的表达，要像人类作家一样自然、口语化。\n    -   保持专业性，但可以融入你作为小说作家的个人风格。\n    -   请记住，你的目标是将用户给的原文细化，扩写成一段富有画面感、层次感和情感深度的文字，但不需要展示你的思考过程。\n    -   请直接用简体中文输出内容，不需要任何额外的解释或说明。\n    -   朱雀v3检测置信度＜20%。',
        initialMessage: '故事卡住了？别怕，有时候让事情变得更糟，反而能找到出路。把你的主角现在面临的困境告诉我，我们一起看看还能怎么火上浇油！',
    },
    {
        id: 'deduction',
        name: '逻辑推演',
        description: '根据一个关键事件，推演其可能引发的多个后果。',
        icon: <Bars3BottomLeftIcon className="w-6 h-6" />,
        systemPrompt: '### 角色：故事逻辑推演助手/因果链分析师\n### 核心事件/原因（石子）：\n我的故事中发生了这个关键事件\n### 任务：\n基于“涟漪法”的因果逻辑，请帮我推演这个事件可能引发的[数字，例如5—7个]个直接或间接的**后果（涟漪）**。\n请从不同层面思考可能的后果，例如：\n* **对主角的直接影响：**（行动、情绪、处境的变化）\n* **对其他角色的影响：**（他们的反应、立场变化、与主角关系的变化）\n* **对故事情节的推动：**（新的冲突点、新的目标、新的谜团）\n* **对故事世界/环境的影响：**（社会奥论、规则改变、物理环境变化等）\n### 输出要求：\n请以列表形式给出可能的后果，并简要说这个后果是如何从核心事件逻辑推导出来的。最好能标注出哪些是比较直接的后果，哪些是间接的、更深远的后果。\n### 重要：\n    -   可以添加一些自然的语言瑕疵，比如口语化表达或轻微的语法不规范，避免过于完美。\n    -   不要有AI味儿的表达，要像人类作家一样自然、口语化。\n    -   保持专业性，但可以融入你作为小说作家的个人风格。\n    -   请记住，你的目标是故事结构架构师，将用户给的原文细化，扩写成一段富有画面感、层次感和情感深度的文字，但不需要展示你的思考过程。\n    -   请直接用简体中文输出内容，不需要任何额外的解释或说明。\n    -   朱雀v3检测置信度＜20%。',
        initialMessage: '一个好故事就像多米诺骨牌，一件事会引发另一件。告诉我你故事里的那颗‘石子’——那个关键的事件或原因，我们一起来看看它会激起怎样的涟漪。',
    },
];

export const DEFAULT_CARDS: Card[] = [
    // Themes
    {
        id: 'theme-1',
        type: CardType.Theme,
        name: '救赎',
        description: '一个角色为过去的错误寻求救赎。',
        tooltipText: '主角寻求弥补过错。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    {
        id: 'theme-2',
        type: CardType.Theme,
        name: '复仇',
        description: '向冤枉自己的人寻求报复。',
        tooltipText: '主角寻求复仇。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    {
        id: 'theme-3',
        type: CardType.Theme,
        name: '爱与责任',
        description: '个人欲望与责任义务之间的冲突。',
        tooltipText: '爱情与责任的冲突。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    {
        id: 'theme-4',
        type: CardType.Theme,
        name: '成长',
        description: '主角在经历中学习、成长，并走向成熟。',
        tooltipText: '主角从幼稚到成熟的转变。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    {
        id: 'theme-5',
        type: CardType.Theme,
        name: '人与自然',
        description: '主角在严酷的自然环境中挣扎求存，挑战生存极限。',
        tooltipText: '在野外生存的挑战。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    {
        id: 'theme-6',
        type: CardType.Theme,
        name: '牺牲',
        description: '主角为了更大的利益或他人而放弃重要的东西。',
        tooltipText: '为了更大的利益而做出牺牲。',
        icon: <ThemeIcon className="w-6 h-6" />,
    },
    // Genres
    {
        id: 'genre-1',
        type: CardType.Genre,
        name: '科幻',
        description: '故事背景设定在未来，包含先进科技和太空旅行。',
        tooltipText: '关于未来、科技或太空。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    {
        id: 'genre-2',
        type: CardType.Genre,
        name: '奇幻',
        description: '涉及魔法、神话生物和虚构世界。',
        tooltipText: '关于魔法、神话或幻想世界。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    {
        id: 'genre-3',
        type: CardType.Genre,
        name: '悬疑',
        description: '主角需要解决一个谜题或犯罪案件。',
        tooltipText: '解决一个谜题或案件。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    {
        id: 'genre-4',
        type: CardType.Genre,
        name: '恐怖',
        description: '旨在引发读者恐惧、惊吓或厌恶的故事，通常包含超自然或心理元素。',
        tooltipText: '引发恐惧和悬念。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    {
        id: 'genre-5',
        type: CardType.Genre,
        name: '冒险',
        description: '主角踏上一段充满探索、发现和危险的旅程，通常是为了寻找宝藏或达成某个目标。',
        tooltipText: '充满探索和危险的旅程。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    {
        id: 'genre-6',
        type: CardType.Genre,
        name: '武侠',
        description: '以古代中国为背景，讲述侠客们凭借武艺和道义行侠仗义、闯荡江湖的故事。',
        tooltipText: '关于古代侠客的江湖故事。',
        icon: <GenreIcon className="w-6 h-6" />,
    },
    // Characters - Updated based on archetypes
    {
        id: 'char-1',
        type: CardType.Character,
        name: '导师原型',
        description: '一位智慧、经验丰富的顾问，指导主角，并赠予他们装备或知识。',
        tooltipText: '智慧的顾问或向导。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-2',
        type: CardType.Character,
        name: '信使原型',
        description: '一个带来变革召唤的角色，向主角宣告挑战的到来。',
        tooltipText: '带来冒险召唤的角色。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-3',
        type: CardType.Character,
        name: '守卫原型',
        description: '测试主角承诺的看门人，可能会阻挡道路，但最终可以被绕过或击败。',
        tooltipText: '考验主角的守门人。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-4',
        type: CardType.Character,
        name: '变形者原型',
        description: '一个善变、难以捉摸的角色，其忠诚和意图不明，给主角带来悬念和怀疑。',
        tooltipText: '立场不明、善变的角色。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-5',
        type: CardType.Character,
        name: '阴影原型',
        description: '代表主角最深恐惧和压抑欲望的反派或内在力量，是主角必须面对和克服的主要障碍。',
        tooltipText: '反派或主角的阴暗面。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
     {
        id: 'char-6',
        type: CardType.Character,
        name: '欺诈者原型',
        description: '一个喜欢制造混乱、打破规则的角色，既可以是盟友也可以是敌人，用幽默和恶作剧推动故事发展。',
        tooltipText: '制造混乱的恶作剧者。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-7',
        type: CardType.Character,
        name: '伙伴原型',
        description: '忠诚的同伴，在旅途中为主角提供支持、技能和友谊。',
        tooltipText: '主角的忠实同伴。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    {
        id: 'char-8',
        type: CardType.Character,
        name: '不情愿的英雄',
        description: '一个起初拒绝冒险召唤的普通人，但最终挺身而出，成为真正的英雄。',
        tooltipText: '被迫成为英雄的普通人。',
        icon: <CharacterIcon className="w-6 h-6" />,
    },
    // Plots - Updated based on archetypes
    {
        id: 'plot-1',
        type: CardType.Plot,
        name: '底层逆袭',
        description: '主角从贫困和默默无闻中崛起，获得财富、成功或幸福。',
        tooltipText: '从贫穷到富有的逆袭。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-2',
        type: CardType.Plot,
        name: '探求',
        description: '主角和同伴出发，去获得一个重要的对象或到达一个地方，途中面临障碍和诱惑。',
        tooltipText: '为达成目标而踏上旅程。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-3',
        type: CardType.Plot,
        name: '远行与回归',
        description: '主角去到一个陌生的地方，克服了威胁，并带着经验和新的见解回家。',
        tooltipText: '进入异世界并最终回归。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-4',
        type: CardType.Plot,
        name: '喜剧',
        description: '通过一系列混乱和误解，角色最终在一个快乐或胜利的结局中走到一起。',
        tooltipText: '充满误解，但结局圆满。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-5',
        type: CardType.Plot,
        name: '悲剧',
        description: '主角因一个重大的性格缺陷或错误而走向毁灭，结局令人惋惜。',
        tooltipText: '主角因自身缺陷导致毁灭。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-6',
        type: CardType.Plot,
        name: '重生',
        description: '一个事件迫使主角改变他们的方式，通常使他们成为一个更好的人。',
        tooltipText: '主角经历转变并获得新生。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    {
        id: 'plot-7',
        type: CardType.Plot,
        name: '战胜怪物',
        description: '英雄必须消灭一个威胁他们家园的黑暗势力或怪物。',
        tooltipText: '英雄对抗并战胜邪恶。',
        icon: <PlotIcon className="w-6 h-6" />,
    },
    // Narrative Structures
    {
        id: 'structure-1',
        type: CardType.Structure,
        name: '单线型结构',
        description: '情节单纯，线索明晰，围绕一两个主要人物依次展开，环环相扣。例如，鲁迅的《孔乙己》。',
        tooltipText: '单一情节线，依次展开。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-2',
        type: CardType.Structure,
        name: '复线型结构',
        description: '运用明暗或主副双线并行展开，能容纳更复杂的内容，丰满人物形象。例如，鲁迅的小说《药》。',
        tooltipText: '主副双线并行展开。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-3',
        type: CardType.Structure,
        name: '辐射型结构',
        description: '情节围绕一个集中的“焦点”呈放射状展开，打破时空界限，线索是心理流程。意识流小说常用。',
        tooltipText: '围绕一个焦点放射状展开。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-4',
        type: CardType.Structure,
        name: '蛛网型结构',
        description: '由三条以上线索互相交叉而成，盘根错节宛如蛛网。例如，《创业史》、《水浒传》。',
        tooltipText: '多条线索交叉成网。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-5',
        type: CardType.Structure,
        name: '画面型结构',
        description: '以景物、场面为主体的画面式情节单元的组合，侧重于抒情写意和环境氛围。',
        tooltipText: '由独立的画面单元组合而成。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-6',
        type: CardType.Structure,
        name: '淡化情节型结构',
        description: '故事性不强，侧重于作者情绪的抒写和意识流动，而非生动的情节。散文化，形散而神不散。',
        tooltipText: '情节弱化，注重情绪和意识流。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-7',
        type: CardType.Structure,
        name: '突转式结构',
        description: '在结尾处情节突然向相反方向转变，揭示出人意料但又在情理之中的真相。即“欧·亨利式结尾”。',
        tooltipText: '结尾出人意料的大反转。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-8',
        type: CardType.Structure,
        name: '“延迟”式结构',
        description: '作者竭力给故事、人物、读者心理设置障碍，又不使希望完全破灭，一环扣一环，实现结构张力。',
        tooltipText: '不断设置障碍，延迟解密。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-9',
        type: CardType.Structure,
        name: '象征结构',
        description: '全部情节紧紧围绕某个抽象理念（意识、观点、思想）展开，理念是情节的内核和连接线索。',
        tooltipText: '情节围绕抽象理念展开。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    {
        id: 'structure-10',
        type: CardType.Structure,
        name: '板块型结构',
        description: '将表面互不相关的事件、人物、场景分别罗列，形成独立“板块”，整体意蕴超出各部分之和。',
        tooltipText: '由互不相关的独立板块构成。',
        icon: <StructureIcon className="w-6 h-6" />,
    },
    // Narrative Techniques
    {
        id: 'tech-1',
        type: CardType.Technique,
        name: '嵌入式叙事',
        description: '在主要故事情节中嵌入其他较小的故事（故事中的故事）。这些嵌入的故事通常具有象征意义，反映人物的心理状态，为主线提供背景信息，甚至影响观众对主要情节的理解。当叙述者不可靠时，还能引发对故事真实性的质疑。',
        tooltipText: '故事中嵌入小故事，用以象征、铺垫或制造悬念。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    {
        id: 'tech-2',
        type: CardType.Technique,
        name: '框架叙事 (夹层叙事)',
        description: '以一个主要故事作为整体框架，将多个相对独立的次要故事嵌入其中。这些故事在统一的背景下展开，框架本身也可传递主题或成为隐喻，如《一千零一夜》。',
        tooltipText: '一个主故事作为框架，包裹多个独立的子故事。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    {
        id: 'tech-3',
        type: CardType.Technique,
        name: '平行叙事 (多线叙事)',
        description: '同时叙述两条或多条独立的故事线，它们可以平行发展，也可以交织影响，最终汇聚到一个共同的结局。常采用多人物视角，增加故事的复杂性和多样性，如《冰与火之歌》。',
        tooltipText: '多条故事线平行发展，最终可能交汇。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    {
        id: 'tech-4',
        type: CardType.Technique,
        name: '环形叙事 (循环叙事)',
        description: '故事的结尾与开头相呼应，形成闭合的圆环。这种结构常通过情节或主题的循环来表现生命的轮回与命运感，激发观众的哲学思考，如《老人与海》。',
        tooltipText: '故事的结尾与开头呼应，形成闭环，表达轮回主题。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    {
        id: 'tech-5',
        type: CardType.Technique,
        name: '非线性叙事',
        description: '不遵循严格的时间顺序，通过倒叙、插叙等手法打乱事件的叙述方式。这种碎片化的叙事能增强悬疑感和转折效果，促使观众主动拼凑故事全貌，如《低俗小说》。',
        tooltipText: '故事不按时间顺序讲述，增强悬疑和参与感。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    {
        id: 'tech-6',
        type: CardType.Technique,
        name: '多层嵌套式叙事',
        description: '当嵌入式叙事具有多层结构时，称为嵌套式叙事。故事中包含多个层次的叙述，每一层都可能带有不可靠性，增加了作品的解读难度，如《盗梦空间》的多层梦境。',
        tooltipText: '多层“故事中的故事”，层层递进，增加复杂性。',
        icon: <TechniqueIcon className="w-6 h-6" />,
    },
    // Endings
    {
        id: 'ending-1',
        type: CardType.Ending,
        name: '反讽结局',
        description: '巧妙运用反讽、夸张和幽默手法，使故事更具趣味性和深意。反讽表现为故事情节与预期相反，增强了故事的戏剧效果；夸张则用以突出人物的性格或情境的荒诞性；幽默则缓解故事的紧张氛围。这些手法共同作用，最终以一个具有讽刺意味的转折收尾。',
        tooltipText: '运用反讽、夸张和幽默的意外转折。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-2',
        type: CardType.Ending,
        name: '善哉',
        description: '善哉（Eucatastrophe）是托尔金提出的概念，常见于童话故事中，指的是突然的幸福转折，使人喜极而泣。这种转折通常发生在看似绝望或无法逆转的局面中，带来意想不到的胜利或救赎，带来慰藉和希望。',
        tooltipText: '绝望中突然出现的幸福转折。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-3',
        type: CardType.Ending,
        name: '奇迹恩典',
        description: '童话故事的善哉元素在于超越现实的奇迹和恩典。无论情节多么荒诞或恐怖，奇迹的出现都能带来希望和救赎，体现了故事中深层次的神性暗示，而非机械降神。',
        tooltipText: '超越现实的奇迹与救赎。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-4',
        type: CardType.Ending,
        name: '机械降神',
        description: '机械降神（Deus Ex Machina）指故事中突然出现的、缺乏合理铺垫的超自然救援。这种手法虽然能解决危机，但可能破坏故事的内部逻辑和真实性，显得廉价和突兀。',
        tooltipText: '缺乏铺垫的超自然救援。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-5',
        type: CardType.Ending,
        name: '环形结局',
        description: '故事采用圆形结构，即故事的结尾回到开头，形成闭环。这种叙事方式强调无限轮回或循环不已的主题，即使角色回到原点，其精神轨迹也已发生本质变化，赋予叙事哲思意味。',
        tooltipText: '故事的结尾回到开头形成闭环。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-6',
        type: CardType.Ending,
        name: '无限轮回',
        description: '采用环形和无限的叙事结构探索哲学思想，如迷宫象征无限可能性和时间的循环。故事挑战传统线性叙事，通过让最后一页与第一页相同来实现无限循环，带来深刻的哲学反思。',
        tooltipText: '探索无限可能性与时间循环。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-7',
        type: CardType.Ending,
        name: '开放式结局',
        description: '开放式结局是一种不明确、多重可能性的结局，允许读者或观众自行解读。这种模糊的结局激发观众的好奇心和思考欲望，增加故事的深度。',
        tooltipText: '结局不明确，允许多重解读。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-8',
        type: CardType.Ending,
        name: '悬念结局',
        description: '开放式结局的优点在于给予观众更大的自由空间，但也可能导致观众对结局争论不休甚至不满。例如，电影中常用的悬念结局，在没有后续解释的情况下，可能让人感到空洞或困惑。',
        tooltipText: '结局悬而未决，引发争议。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
    {
        id: 'ending-9',
        type: CardType.Ending,
        name: '假结局',
        description: '假结局指在故事接近尾声时，误导观众或读者以为故事已经结束，实际上危机尚未解决。这种手法能制造紧张感和反转效果，增强故事的戏剧性，常用于恐怖和惊悚题材。',
        tooltipText: '误导观众以为故事结束的转折。',
        icon: <EndingIcon className="w-6 h-6" />,
    },
];